### ISSUE TITLE
部署时提示Error: Cannot find module 'sync-request'

### ISSUE THREAD

**Issue by Taoqiong** [analysys/ans-node-sdk#2]
如题
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'sync-request'
Require stack:
- /[目录]/node_modules/_ans-node-sdk@4.0.6@ans-node-sdk/sdk/AnalysysAgent_NodeJS_SDK.cjs.js
- /[目录]/helpers/fzAnalysys_helper.js
- /[目录]/helpers/mall_helper.js
- /[目录]/controllers/gitchat/column_controller.js
- /[目录]/routes/index.js
- /[目录]/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/[目录]/node_modules/_ans-node-sdk@4.0.6@ans-node-sdk/sdk/AnalysysAgent_NodeJS_SDK.cjs.js:5:31)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/[目录]/helpers/fzAnalysys_helper.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/[目录]/node_modules/_ans-node-sdk@4.0.6@ans-node-sdk/sdk/AnalysysAgent_NodeJS_SDK.cjs.js',
    '/[目录]/helpers/fzAnalysys_helper.js',
    '/[目录]/helpers/mall_helper.js',
    '/[目录]/controllers/gitchat/column_controller.js',
    '/[目录]/routes/index.js',
    '/[目录]/app.js'
  ]
}
上线失败了，故回滚。错误日志如上👆。
看了下最新的commit，依赖由request改为了sync-request，在package.json中把依赖写到了devDependencies里。
而部署生产环境时不会安装decDependencies，导致服务没起来。
忘纠正啊哈。

**Comment by OMGMountain** [comment]
谢谢指正，package.json 中依赖已经更新
